/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.util.views.cadastros;

import br.edu.imepac.entidades.C_funcionarios;
import java.util.Scanner;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author Matheus Carrasco
 */
public class Funcionarios extends javax.swing.JFrame {
    
    
    Scanner sc = new Scanner(System.in);
   

    /*
     * Creates new form Funcionarios
     */
    public Funcionarios() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeScan = new javax.swing.JTextField();
        nomeCompleto = new java.awt.Label();
        numRG = new java.awt.Label();
        RGScan = new javax.swing.JTextField();
        orgaoEmissor = new java.awt.Label();
        orgaoEmissorScan = new javax.swing.JTextField();
        CPF = new java.awt.Label();
        cadastrarFuncionario = new javax.swing.JButton();
        endereco = new java.awt.Label();
        enderecoScan = new javax.swing.JTextField();
        numero = new java.awt.Label();
        complemento = new java.awt.Label();
        complementoScan = new javax.swing.JTextField();
        bairro = new java.awt.Label();
        bairroScan = new javax.swing.JTextField();
        cidade = new java.awt.Label();
        cidadeScan = new javax.swing.JTextField();
        estado = new java.awt.Label();
        estadoScan = new javax.swing.JTextField();
        telefone = new java.awt.Label();
        telefoneScan = new javax.swing.JTextField();
        celular = new java.awt.Label();
        celularScan = new javax.swing.JTextField();
        dataNascimento = new java.awt.Label();
        diaScan = new javax.swing.JTextField();
        numCTPS = new java.awt.Label();
        numCTPSScan = new javax.swing.JTextField();
        numPISScan = new javax.swing.JTextField();
        numPIS = new java.awt.Label();
        cpfScan = new javax.swing.JTextField();
        numScan = new javax.swing.JTextField();
        sexo = new java.awt.Label();
        sexoScan = new javax.swing.JTextField();
        mesScan = new javax.swing.JTextField();
        anoScan = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomeScan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nomeScan.setText("nomeScan");

        nomeCompleto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nomeCompleto.setName(""); // NOI18N
        nomeCompleto.setPreferredSize(new java.awt.Dimension(40, 20));
        nomeCompleto.setText("Nome Completo: ");

        numRG.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        numRG.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        numRG.setName(""); // NOI18N
        numRG.setPreferredSize(new java.awt.Dimension(40, 20));
        numRG.setText("Nº RG:");

        RGScan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        RGScan.setText("RGScan");

        orgaoEmissor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        orgaoEmissor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        orgaoEmissor.setName(""); // NOI18N
        orgaoEmissor.setPreferredSize(new java.awt.Dimension(40, 20));
        orgaoEmissor.setText("Orgão Emissor: ");

        orgaoEmissorScan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        orgaoEmissorScan.setText("OEScan");

        CPF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CPF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CPF.setName(""); // NOI18N
        CPF.setPreferredSize(new java.awt.Dimension(40, 20));
        CPF.setText("CPF:");

        cadastrarFuncionario.setText("CADASTRAR");
        cadastrarFuncionario.setAlignmentY(0.0F);
        cadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFuncionarioActionPerformed(evt);
            }
        });

        endereco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        endereco.setName(""); // NOI18N
        endereco.setPreferredSize(new java.awt.Dimension(40, 20));
        endereco.setText("Endereço: ");

        enderecoScan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        enderecoScan.setText("enderecoScan");
        enderecoScan.setToolTipText("");

        numero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        numero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        numero.setName(""); // NOI18N
        numero.setPreferredSize(new java.awt.Dimension(40, 20));
        numero.setText("nº:");

        complemento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        complemento.setName(""); // NOI18N
        complemento.setPreferredSize(new java.awt.Dimension(40, 20));
        complemento.setText("Complemento:");

        complementoScan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        complementoScan.setText("enderecoScan");
        complementoScan.setToolTipText("");

        bairro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bairro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bairro.setName(""); // NOI18N
        bairro.setPreferredSize(new java.awt.Dimension(40, 20));
        bairro.setText("Bairro:");

        bairroScan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bairroScan.setText("bairroScan");

        cidade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cidade.setName(""); // NOI18N
        cidade.setPreferredSize(new java.awt.Dimension(40, 20));
        cidade.setText("Cidade:");

        cidadeScan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cidadeScan.setText("cidadeScan");

        estado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        estado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        estado.setName(""); // NOI18N
        estado.setPreferredSize(new java.awt.Dimension(40, 20));
        estado.setText("Estado:");

        estadoScan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        estadoScan.setText("estadoScan");

        telefone.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        telefone.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        telefone.setName(""); // NOI18N
        telefone.setPreferredSize(new java.awt.Dimension(40, 20));
        telefone.setText("Telefone:");

        telefoneScan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        telefoneScan.setText("telefoneScan");

        celular.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        celular.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        celular.setName(""); // NOI18N
        celular.setPreferredSize(new java.awt.Dimension(40, 20));
        celular.setText("Celular:");

        celularScan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        celularScan.setText("celularScan");

        dataNascimento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dataNascimento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dataNascimento.setName(""); // NOI18N
        dataNascimento.setPreferredSize(new java.awt.Dimension(40, 20));
        dataNascimento.setText("Data Nascimento [dia/mes/ano]:");

        diaScan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        diaScan.setText("diaScan");

        numCTPS.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        numCTPS.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        numCTPS.setName(""); // NOI18N
        numCTPS.setPreferredSize(new java.awt.Dimension(40, 20));
        numCTPS.setText("nº CTPS: ");

        numCTPSScan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        numCTPSScan.setText("numCTPSScan");

        numPISScan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        numPISScan.setText("numPISScan");

        numPIS.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        numPIS.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        numPIS.setName(""); // NOI18N
        numPIS.setPreferredSize(new java.awt.Dimension(40, 20));
        numPIS.setText("nº PIS: ");

        cpfScan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cpfScan.setText("cpfScan");

        numScan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        numScan.setText("numScan");

        sexo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sexo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        sexo.setName(""); // NOI18N
        sexo.setPreferredSize(new java.awt.Dimension(40, 20));
        sexo.setText("Sexo:");

        sexoScan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        sexoScan.setText("sexoScan");

        mesScan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mesScan.setText("mesScan");

        anoScan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        anoScan.setText("mesScan");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numCTPS, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numCTPSScan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numPIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numPISScan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RGScan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orgaoEmissor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(orgaoEmissorScan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpfScan))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(complementoScan))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enderecoScan, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numScan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeScan, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(sexoScan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bairroScan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(celularScan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(telefoneScan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(diaScan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mesScan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(anoScan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cidadeScan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estadoScan, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(cadastrarFuncionario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomeScan)
                    .addComponent(nomeCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexoScan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RGScan)
                            .addComponent(numRG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orgaoEmissor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orgaoEmissorScan))
                        .addComponent(CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cpfScan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(enderecoScan)
                        .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numScan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(complementoScan)
                    .addComponent(complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bairroScan)
                            .addComponent(bairro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cidadeScan)
                            .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(estadoScan)
                        .addComponent(estado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(telefoneScan)
                            .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(celularScan)
                            .addComponent(celular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(diaScan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mesScan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(anoScan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(numCTPSScan)
                        .addComponent(numCTPS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(numPISScan, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(numPIS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(cadastrarFuncionario)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncionarioActionPerformed
         C_funcionarios funcionario = new C_funcionarios(   1, numCTPSScan.getText(),
                                                            numPISScan.getText(), 
                                                            nomeScan.getText(), 
                                                            RGScan.getText(), 
                                                            orgaoEmissorScan.getText(), 
                                                            cpfScan.getText(), 
                                                            enderecoScan.getText(), 
                                                            numScan.getText(), 
                                                            complementoScan.getText(), 
                                                            bairroScan.getText(), 
                                                            cidadeScan.getText(), 
                                                            estadoScan.getText(), 
                                                            telefoneScan.getText(), 
                                                            celularScan.getText(), 
                                                            sexoScan.getText(), 
                                                            diaScan.getText(), 
                                                            mesScan.getText(), 
                                                            anoScan.getText());
        
         JOptionPane.showMessageDialog(null, funcionario, "Alerta", ERROR_MESSAGE);
    }//GEN-LAST:event_cadastrarFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funcionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label CPF;
    private javax.swing.JTextField RGScan;
    private javax.swing.JTextField anoScan;
    private java.awt.Label bairro;
    private javax.swing.JTextField bairroScan;
    private javax.swing.JButton cadastrarFuncionario;
    private java.awt.Label celular;
    private javax.swing.JTextField celularScan;
    private java.awt.Label cidade;
    private javax.swing.JTextField cidadeScan;
    private java.awt.Label complemento;
    private javax.swing.JTextField complementoScan;
    private javax.swing.JTextField cpfScan;
    private java.awt.Label dataNascimento;
    private javax.swing.JTextField diaScan;
    private java.awt.Label endereco;
    private javax.swing.JTextField enderecoScan;
    private java.awt.Label estado;
    private javax.swing.JTextField estadoScan;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField mesScan;
    private java.awt.Label nomeCompleto;
    private javax.swing.JTextField nomeScan;
    private java.awt.Label numCTPS;
    private javax.swing.JTextField numCTPSScan;
    private java.awt.Label numPIS;
    private javax.swing.JTextField numPISScan;
    private java.awt.Label numRG;
    private javax.swing.JTextField numScan;
    private java.awt.Label numero;
    private java.awt.Label orgaoEmissor;
    private javax.swing.JTextField orgaoEmissorScan;
    private java.awt.Label sexo;
    private javax.swing.JTextField sexoScan;
    private java.awt.Label telefone;
    private javax.swing.JTextField telefoneScan;
    // End of variables declaration//GEN-END:variables
}
