/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.views.iniciais;

import br.edu.imepac.DAO.Usuarios;
import br.edu.imepac.views.cadastros.AgendarConsulta;
import br.edu.imepac.views.cadastros.CadastroConvenio;
import br.edu.imepac.views.cadastros.CadastroEspecialidades;
import br.edu.imepac.views.cadastros.CadastroFuncionarios;
import br.edu.imepac.views.cadastros.CadastroMedico;
import br.edu.imepac.views.cadastros.CadastroPacientes;
import br.edu.imepac.views.cadastros.CadastroUsuario;
import br.edu.imepac.views.localizar.LocalizarAgendamento;
import br.edu.imepac.views.localizar.LocalizarConvenio;
import br.edu.imepac.views.localizar.LocalizarEspecialidade;
import br.edu.imepac.views.localizar.LocalizarFuncionario;
import br.edu.imepac.views.localizar.LocalizarMedico;
import br.edu.imepac.views.localizar.LocalizarPaciente;
import br.edu.imepac.views.localizar.LocalizarUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus Carrasco
 */
public class TelaInicial extends javax.swing.JFrame {
    
    Usuarios user = new Usuarios();

    /**
     * Creates new form viewLogin
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        adicionarFuncionario = new javax.swing.JMenuItem();
        localizarFuncionario = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        adicionarUsuario = new javax.swing.JMenuItem();
        localizarUsuario = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        adicionarEspecialidade = new javax.swing.JMenuItem();
        localizarEspecialidade = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        adicionarMedicos = new javax.swing.JMenuItem();
        localizarMedicos = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        adicionarConvenio = new javax.swing.JMenuItem();
        localizarConvenio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        adicionarPaciente = new javax.swing.JMenuItem();
        localizarPaciente = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        adicionarConsulta = new javax.swing.JMenuItem();
        cancelarConsulta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        jMenu1.setText("Administrativo");

        jMenu4.setText("Funcionários");

        adicionarFuncionario.setText("Adicionar");
        adicionarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarFuncionarioActionPerformed(evt);
            }
        });
        jMenu4.add(adicionarFuncionario);

        localizarFuncionario.setText("Localizar");
        localizarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localizarFuncionarioActionPerformed(evt);
            }
        });
        jMenu4.add(localizarFuncionario);

        jMenu1.add(jMenu4);

        jMenu5.setText("Usuários");

        adicionarUsuario.setText("Adicionar");
        adicionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarUsuarioActionPerformed(evt);
            }
        });
        jMenu5.add(adicionarUsuario);

        localizarUsuario.setText("Localizar");
        localizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localizarUsuarioActionPerformed(evt);
            }
        });
        jMenu5.add(localizarUsuario);

        jMenu1.add(jMenu5);

        jMenu6.setText("Especialidade");

        adicionarEspecialidade.setText("Adicionar");
        adicionarEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarEspecialidadeActionPerformed(evt);
            }
        });
        jMenu6.add(adicionarEspecialidade);

        localizarEspecialidade.setText("Localizar");
        localizarEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localizarEspecialidadeActionPerformed(evt);
            }
        });
        jMenu6.add(localizarEspecialidade);

        jMenu1.add(jMenu6);

        jMenu7.setText("Médicos");

        adicionarMedicos.setText("Adicionar");
        adicionarMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarMedicosActionPerformed(evt);
            }
        });
        jMenu7.add(adicionarMedicos);

        localizarMedicos.setText("Localizar");
        localizarMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localizarMedicosActionPerformed(evt);
            }
        });
        jMenu7.add(localizarMedicos);

        jMenu1.add(jMenu7);

        jMenu8.setText("Convenios");

        adicionarConvenio.setText("Adicionar");
        adicionarConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarConvenioActionPerformed(evt);
            }
        });
        jMenu8.add(adicionarConvenio);

        localizarConvenio.setText("Localizar");
        localizarConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localizarConvenioActionPerformed(evt);
            }
        });
        jMenu8.add(localizarConvenio);

        jMenu1.add(jMenu8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Agendamento");

        jMenu10.setText("Paciente");

        adicionarPaciente.setText("Adicionar");
        adicionarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarPacienteActionPerformed(evt);
            }
        });
        jMenu10.add(adicionarPaciente);

        localizarPaciente.setText("Localizar");
        localizarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localizarPacienteActionPerformed(evt);
            }
        });
        jMenu10.add(localizarPaciente);

        jMenu2.add(jMenu10);

        jMenu11.setText("Agendamento");

        adicionarConsulta.setText("Adicionar");
        adicionarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarConsultaActionPerformed(evt);
            }
        });
        jMenu11.add(adicionarConsulta);

        cancelarConsulta.setText("Localizar");
        cancelarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarConsultaActionPerformed(evt);
            }
        });
        jMenu11.add(cancelarConsulta);

        jMenu2.add(jMenu11);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Atendimento");

        jMenu13.setText("Registro");

        jMenuItem5.setText("Adicionar");
        jMenu13.add(jMenuItem5);

        jMenuItem16.setText("Localizar");
        jMenu13.add(jMenuItem16);

        jMenu3.add(jMenu13);

        jMenuBar1.add(jMenu3);

        jMenu9.setText("Sair");
        jMenu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu9ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarEspecialidadeActionPerformed
        new CadastroEspecialidades().setVisible(true);       
    }//GEN-LAST:event_adicionarEspecialidadeActionPerformed

    private void adicionarMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarMedicosActionPerformed
        new CadastroMedico().setVisible(true);        
    }//GEN-LAST:event_adicionarMedicosActionPerformed

    private void adicionarConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarConvenioActionPerformed
        new CadastroConvenio().setVisible(true);
    }//GEN-LAST:event_adicionarConvenioActionPerformed

    private void adicionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarUsuarioActionPerformed
        new CadastroUsuario().setVisible(true);
    }//GEN-LAST:event_adicionarUsuarioActionPerformed

    private void adicionarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarFuncionarioActionPerformed
        new CadastroFuncionarios().setVisible(true);
    }//GEN-LAST:event_adicionarFuncionarioActionPerformed

    private void localizarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localizarFuncionarioActionPerformed
        new LocalizarFuncionario().setVisible(true);
    }//GEN-LAST:event_localizarFuncionarioActionPerformed

    private void localizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localizarUsuarioActionPerformed
        new LocalizarUsuario().setVisible(true);
    }//GEN-LAST:event_localizarUsuarioActionPerformed

    private void localizarEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localizarEspecialidadeActionPerformed
        new LocalizarEspecialidade().setVisible(true);
    }//GEN-LAST:event_localizarEspecialidadeActionPerformed

    private void localizarMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localizarMedicosActionPerformed
        new LocalizarMedico().setVisible(true);
    }//GEN-LAST:event_localizarMedicosActionPerformed

    private void localizarConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localizarConvenioActionPerformed
        new LocalizarConvenio().setVisible(true);
    }//GEN-LAST:event_localizarConvenioActionPerformed

    private void jMenu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu9ActionPerformed
        new TelaLogin().setVisible(true);
    }//GEN-LAST:event_jMenu9ActionPerformed

    private void adicionarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarPacienteActionPerformed
        new CadastroPacientes().setVisible(true);
    }//GEN-LAST:event_adicionarPacienteActionPerformed

    private void localizarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localizarPacienteActionPerformed
        new LocalizarPaciente().setVisible(true);
        
    }//GEN-LAST:event_localizarPacienteActionPerformed

    private void adicionarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarConsultaActionPerformed
        new AgendarConsulta().setVisible(true);
    }//GEN-LAST:event_adicionarConsultaActionPerformed

    private void cancelarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarConsultaActionPerformed
        new LocalizarAgendamento().setVisible(true);       
    }//GEN-LAST:event_cancelarConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem adicionarConsulta;
    private javax.swing.JMenuItem adicionarConvenio;
    private javax.swing.JMenuItem adicionarEspecialidade;
    private javax.swing.JMenuItem adicionarFuncionario;
    private javax.swing.JMenuItem adicionarMedicos;
    private javax.swing.JMenuItem adicionarPaciente;
    private javax.swing.JMenuItem adicionarUsuario;
    private javax.swing.JMenuItem cancelarConsulta;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem localizarConvenio;
    private javax.swing.JMenuItem localizarEspecialidade;
    private javax.swing.JMenuItem localizarFuncionario;
    private javax.swing.JMenuItem localizarMedicos;
    private javax.swing.JMenuItem localizarPaciente;
    private javax.swing.JMenuItem localizarUsuario;
    // End of variables declaration//GEN-END:variables
}
