/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.views.alterar;

import br.edu.imepac.views.cadastros.*;
import br.edu.imepac.DAO.ConexaoBancoDeDados;
import br.edu.imepac.views.iniciais.TelaInicial;
import br.edu.imepac.DAO.Usuarios;
import br.edu.imepac.entidades.C_usuarios;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author Matheus Carrasco
 */
public class AlterarUsuario extends javax.swing.JFrame {
    
    C_usuarios usuario = new C_usuarios();

    /**
     * Creates new form viewLogin
     */
    public AlterarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cadastrar = new java.awt.Button();
        userText = new javax.swing.JTextField();
        cadConvenio = new javax.swing.JCheckBox();
        cadFuncionario = new javax.swing.JCheckBox();
        cadUsuario = new javax.swing.JCheckBox();
        cadEspecialidade = new javax.swing.JCheckBox();
        cadMedicos = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        cadPacientes = new javax.swing.JCheckBox();
        agenConsultas = new javax.swing.JCheckBox();
        cancelConsultas = new javax.swing.JCheckBox();
        passwordText = new javax.swing.JPasswordField();
        moduloAtendimento = new javax.swing.JCheckBox();
        moduloAdministrativo = new javax.swing.JCheckBox();
        moduloAgendamento = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(66, 141, 255));
        jLabel2.setText("ALTERAR USUÁRIO");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Usuário:");

        cadastrar.setBackground(new java.awt.Color(164, 194, 247));
        cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cadastrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cadastrar.setForeground(new java.awt.Color(66, 141, 255));
        cadastrar.setLabel("Alterar");
        cadastrar.setName(""); // NOI18N
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        userText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cadConvenio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadConvenio.setText("Cadastro de Convênios");

        cadFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadFuncionario.setText("Cadastro de Funcionários");

        cadUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadUsuario.setText("Cadastro de Usuários");

        cadEspecialidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadEspecialidade.setText("Cadastro de Especialidades");

        cadMedicos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadMedicos.setText("Cadastro de Médicos");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Senha:");

        cadPacientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadPacientes.setText("Cadastro de Pacientes");

        agenConsultas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        agenConsultas.setText("Agendamento de Consultas");

        cancelConsultas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cancelConsultas.setText("Cancelamento de Consultas");

        passwordText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        moduloAtendimento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        moduloAtendimento.setText("Modulo Atendimento");

        moduloAdministrativo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        moduloAdministrativo.setText("Modulo Administrativo");

        moduloAgendamento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        moduloAgendamento.setText("Modulo Agendamento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(390, 390, 390))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordText)
                            .addComponent(userText, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadEspecialidade)
                            .addComponent(cadFuncionario)
                            .addComponent(cadUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moduloAdministrativo)
                            .addComponent(cadMedicos)
                            .addComponent(cadConvenio))
                        .addGap(141, 141, 141)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(agenConsultas)
                            .addComponent(cadPacientes)
                            .addComponent(moduloAgendamento)
                            .addComponent(cancelConsultas, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(92, 92, 92)
                        .addComponent(moduloAtendimento)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(377, 377, 377))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userText)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(moduloAtendimento))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moduloAgendamento)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadPacientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agenConsultas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelConsultas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(moduloAdministrativo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadEspecialidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadMedicos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadConvenio)
                        .addGap(97, 97, 97))))
        );

        jMenu9.setText("Inicio");
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jMenu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu9ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu9);

        jMenu10.setText("Sair");
        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu9MouseClicked

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        
        if(verificaUsuarioESenhaEmBranco()){
            usuario.setIdUsuario(userText.getText());
            usuario.setSenhaAcesso(new String(passwordText.getPassword()));
            String validacao; 
            if (cadFuncionario.isSelected()){
                validacao = "S";
                usuario.setCadastroFuncionario(validacao);
            }else{
                validacao = "N";
                usuario.setCadastroFuncionario(validacao);
            }

            if (cadUsuario.isSelected()){
                validacao = "S";
                usuario.setCadastroUsuario(validacao);
            }else{
                validacao = "N";
                usuario.setCadastroUsuario(validacao);
            }

            if (cadEspecialidade.isSelected()){
                validacao = "S";
                usuario.setCadastroEspecialidade(validacao);
            }else{
                validacao = "N";
                usuario.setCadastroEspecialidade(validacao);
            }

            if (cadMedicos.isSelected()){
                validacao = "S";
                usuario.setCadastroMedico(validacao);
            }else{
                validacao = "N";
                usuario.setCadastroMedico(validacao);
            }

            if (cadConvenio.isSelected()){
                validacao = "S";
                usuario.setCadastroConvenio(validacao);
            }else{
                validacao = "N";
                usuario.setCadastroConvenio(validacao);
            }

            if (cadPacientes.isSelected()){
                validacao = "S";
                usuario.setCadastroPaciente(validacao);
            }else{
                validacao = "N";
                usuario.setCadastroPaciente(validacao);
            }

            if (agenConsultas.isSelected()){
                validacao = "S";
                usuario.setAgendamentoConsulta(validacao);
            }else{
                validacao = "N";
                usuario.setAgendamentoConsulta(validacao);
            }

            if (cancelConsultas.isSelected()){
                validacao = "S";
                usuario.setCancelamentoConsulta(validacao);
            }else{
                validacao = "N";
                usuario.setCancelamentoConsulta(validacao);
            }

            if (moduloAtendimento.isSelected()){
                validacao = "S";
                usuario.setModuloAtendimento(validacao);
            }else{
                validacao = "N";
                usuario.setModuloAtendimento(validacao);
            }
            
            if (moduloAdministrativo.isSelected()){
                validacao = "S";
                usuario.setModuloAdministrativo(validacao);
            }else{
                validacao = "N";
                usuario.setModuloAdministrativo(validacao);
            }
            
            if (moduloAgendamento.isSelected()){
                validacao = "S";
                usuario.setModuloAgendamento(validacao);
            }else{
                validacao = "N";
                usuario.setModuloAgendamento(validacao);
            }
            
            try{
                ConexaoBancoDeDados conexao = new ConexaoBancoDeDados();
                Usuarios user = new Usuarios();
                
                if(conexao.abrirConexao()){
                    user.configurarConexao(conexao.obterConexao());
                    if(user.inserirRegistro(usuario)){                                    
                        JOptionPane.showMessageDialog(null, "Usuário "
                         + usuario.getIdUsuario() + " cadastrado com sucesso."); 
                    }else{
                        JOptionPane.showMessageDialog(null, ""
                        + "Não foi possivel cadastrar o usuário", "Alerta", 
                         ERROR_MESSAGE);
                    }
                    conexao.fecharConexao();
                }else{
                        JOptionPane.showMessageDialog(null, ""
                        + "Não foi possivel estabelecer conexão com o banco de dados!"
                        , "Alerta", ERROR_MESSAGE);
                }
            }catch(Exception erro){
                erro.printStackTrace();
                JOptionPane.showMessageDialog(null, ""
                + "Erro do sistema: processo de cadastro de usuário"
                , "Alerta", ERROR_MESSAGE);
            }  
        }
    }//GEN-LAST:event_cadastrarActionPerformed

    private void jMenu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu9ActionPerformed
        new TelaInicial().setVisible(true);
    }//GEN-LAST:event_jMenu9ActionPerformed

    public boolean verificaUsuarioESenhaEmBranco(){
        if (userText.getText().isBlank() || userText.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo "
                    + "usuário é obrigatório e deve ser preenchido!", "Alerta",
                    ERROR_MESSAGE);  
            return false;
        }
        if (passwordText.getPassword().length == 0) {
            JOptionPane.showMessageDialog(null, "Campo "
                    + "senha é obrigatório e deve ser preenchido!", "Alerta", 
                    ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox agenConsultas;
    private javax.swing.JCheckBox cadConvenio;
    private javax.swing.JCheckBox cadEspecialidade;
    private javax.swing.JCheckBox cadFuncionario;
    private javax.swing.JCheckBox cadMedicos;
    private javax.swing.JCheckBox cadPacientes;
    private javax.swing.JCheckBox cadUsuario;
    private java.awt.Button cadastrar;
    private javax.swing.JCheckBox cancelConsultas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox moduloAdministrativo;
    private javax.swing.JCheckBox moduloAgendamento;
    private javax.swing.JCheckBox moduloAtendimento;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables
}
